export const ACTION_LOGIN = 'AUTH/ACTION_LOGIN';
export const ACTION_SIGNUP = 'AUTH/ACTION_SIGNUP';
export const ACTION_LOGOUT = 'AUTH/ACTION_LOGOUT';
export const ACTION_AUTH_LOADING = 'AUTH/ACTION_LOADING';
export const ACTION_AUTH_LOADED = 'AUTH/ACTION_LOADED';