export const ACTION_ADD_FIELDS_TO_FORM_CREATE_ORDER = 'ORDER/ACTION_ADD_FIELDS_TO_FORM_CREATE_ORDER';
export const ACTION_ADD_ORDER_TO_LIST = 'ORDER/ACTION_ADD_ORDER_TO_LIST';
export const ADD_ERROR_BY_VALIDATION = 'ORDER/ADD_ERROR_BY_VALIDATION';
export const ACTION_ADD_ORDERS_LIST = 'ORDER/ACTION_ADD_ORDERS_LIST';
export const ACTION_ADD_ORDER = 'ORDER/ACTION_ADD_ORDER';
